server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://telco-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: telco-app-filelogs
    pipeline_stages:
      - drop:
          expression: 'GET /(health|metrics|docs|redoc)(\\?.*)? '
    static_configs:
      - targets:
          - localhost
        labels:
          job: telco-churn
          app: telco-churn-api
          service: app
          __path__: /var/log/telco/*.log
